FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements/train.txt .
RUN pip install --no-cache-dir -r train.txt

COPY src/ /app/src/
COPY configs/ /app/configs/

ENTRYPOINT ['python', '/app/src/train.py']
