FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements/serve.txt .
RUN pip install --no-cache-dir -r serve.txt

COPY src/ /app/src/
COPY ./cifar10_model.pt /app/cifar10_model.pt
COPY configs/ /app/configs/

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD curl -f http://localhost:8080/health || exit 1

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]