name: MLOPS Pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  training:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Train model
        run: |
          set -euo pipefail

          docker build \
            -f docker/Dockerfile.train \
            -t mlops-train .

          docker create \
            --name mlops-train-run \
            mlops-train

          docker start -a mlops-train-run

          docker cp \
            mlops-train-run:/app/checkpoints/cifar10_model.pt \
            cifar10_model.pt

          docker rm mlops-train-run

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: cifar10-model
          path: cifar10_model.pt

      - name: Serve model
        run: |
          set -euo pipefail

          docker build \
            -f docker/Dockerfile.serve \
            -t mlops-serve .

          docker run -d \
            --name mlops-serve-run \
            mlops-serve

          docker ps \
            --filter name=mlops-serve-run
