name: MLOPS Pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: repo checkout
        uses: actions/checkout@v5

      - name: authenticate gcp
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          create_credentials_file: true
          export_environment_variables: true

      - name: setup google cloud sdk
        uses: google-github-actions/setup-gcloud@v3

      - name: provision instance
        run: |
          if gcloud compute instances describe "ga-instance" --zone=us-central1-b > /dev/null 2>&1; then
            echo "Instance already exists!"
            gcloud compute instances start "ga-instance" --zone=us-central1-b
          else
            echo "Instance not found. Creating a new instance..."
            gcloud compute instances create "ga-instance" \
              --zone=us-central1-b \
              --source-instance-template=ga-gpu-spot-instance-template \
              --metadata=block-project-ssh-keys=TRUE,enable-oslogin=FALSE,startup-script="mkdir actions-runner && cd actions-runner && curl -O -L https://github.com/actions/runner/releases/download/v2.336.0/actions-runner-linux-x64-2.336.0.tar.gz && tar xzf ./actions-runner-linux-x64-2.336.0.tar.gz && ./config.sh --url https://github.com/varunanven/mlops-pytorch-pipeline --token ${{ secrets.PERSONAL_ACCESS_TOKEN }} --labels ga-spot-instance --unattended && ./run.sh"
          fi

  training:
    needs: setup
    runs-on: [self-hosted, ga-spot-instance]
    steps:
      - name: repo checkout
        uses: actions/checkout@v5

      - name: execute model train
        run: python3 train.py

      - name: set checkpoint
        uses: actions/upload-artifact@v4
        with:
          name: l4-spot-weights
          path: model.pth

  cleanup:
    needs: [setup, training]
    runs-on: ubuntu-latest
    steps:
      - name: shutdown instance
        run: |
          gcloud compute instances delete ga-runner-{{ github.run_id }} --zone=us-central1-a --quiet